server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/whiskychuchu?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: shsh
    password: shsh
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      amazonaws:
        util:
        EC2MetadataUtils: error