spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:mysql://${endpoint}:${port}/${db}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
admin:
  username: ${adminUsername}
  password: ${adminPassword}