spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        order_inserts:  true
        order_updates:  true
        jdbc:
          batch_size: 100
url:
  lotte:  https://www.lotteon.com/search/render/render.ecn?render=nqapi&platform=pc&collection_id=301&login=Y&u9=navigate&u8=LM90150163&mallId=4
file:
  dir:  C:\\whisky\\
cloud:
  aws:
    s3:
      bucket: ${bucket}
    credentials:
      access-key: ${accessKey}
      secret-key: ${secretKey}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false